/**
 * @file seedDatabase.ts
 * @description Static fallback medicine dataset used when persisted data is missing or reset is requested.
 * @module Database
 */
import type { Medicine } from '../store/useAppStore';

export const seedMedicines: Medicine[] = [
  {
    id: 'paracetamol',
    name: 'Paracetamol',
    genericName: 'Acetaminophen',
    class: 'Analgesic / Antipyretic',
    category: 'Pain & Fever',
    uses: ['Fever', 'Headache', 'Muscle aches', 'Mild to moderate pain'],
    dosage: {
      adult: '500-1000 mg every 4-6 hours as needed. Max 4000 mg/day (often 3000 mg/day if frequent use).',
      pediatric: '10-15 mg/kg per dose every 4-6 hours as needed. Do not exceed 5 doses in 24 hours.',
      elderly: 'Use the lowest effective dose; consider max 3000 mg/day if long-term or frail.',
    },
    sideEffects: {
      common: ['Usually well tolerated at recommended doses'],
      rare: ['Liver injury with overdose or with heavy alcohol use', 'Serious rash (very rare)'],
    },
    pregnancySafety: 'Commonly used in pregnancy when needed. Use the lowest effective dose and shortest duration.',
    interactions: ['Alcohol (increases liver risk)', 'Warfarin (high regular doses may increase INR)'],
    warnings: [
      'Many cold/flu products contain paracetamol. Avoid doubling up.',
      'Seek urgent help if overdose is suspected.',
    ],
    contraindications: ['Severe liver disease'],
  },
  {
    id: 'ibuprofen',
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    class: 'NSAID',
    category: 'Pain & Inflammation',
    uses: ['Pain', 'Inflammation', 'Fever', 'Menstrual cramps'],
    dosage: {
      adult: '200-400 mg every 6-8 hours with food as needed. Max 1200 mg/day OTC (higher only if prescribed).',
      pediatric: '5-10 mg/kg per dose every 6-8 hours as needed. Max 40 mg/kg/day.',
      elderly: 'Use lowest effective dose; higher GI and kidney risk.',
    },
    sideEffects: {
      common: ['Stomach upset', 'Heartburn', 'Nausea'],
      rare: ['Stomach bleeding/ulcer', 'Kidney injury', 'Allergic reaction (wheezing, swelling)'],
    },
    pregnancySafety: 'Avoid in the 3rd trimester. Earlier pregnancy only if advised by a clinician.',
    interactions: ['Aspirin (may reduce cardioprotective effect)', 'Warfarin', 'ACE inhibitors/diuretics (kidney risk)'],
    warnings: ['Take with food.', 'Avoid if you have a history of ulcers or GI bleeding unless advised.'],
    contraindications: ['Active GI bleeding', 'NSAID allergy', 'Severe kidney disease'],
  },
  {
    id: 'aspirin',
    name: 'Aspirin',
    genericName: 'Acetylsalicylic acid',
    class: 'NSAID / Antiplatelet',
    category: 'Pain & Cardiovascular',
    uses: ['Pain (some cases)', 'Fever (adults)', 'Prevention of blood clots (low dose, clinician-directed)'],
    dosage: {
      adult: 'Pain/fever: 325-650 mg every 4-6 hours with food. Antiplatelet: commonly 75-100 mg daily (clinician-directed).',
      pediatric: 'Not recommended for viral illness due to Reye syndrome risk unless clinician-directed.',
      elderly: 'Higher bleeding risk; confirm indication and dose with clinician.',
    },
    sideEffects: {
      common: ['Heartburn', 'Nausea', 'Easy bruising'],
      rare: ['Serious bleeding', 'Tinnitus at high doses', 'Allergic reaction'],
    },
    pregnancySafety: 'Avoid regular/high doses in pregnancy unless specifically prescribed.',
    interactions: ['Warfarin', 'Other NSAIDs', 'Alcohol', 'Steroids (GI bleeding risk)'],
    warnings: ['Do not use for children with viral symptoms unless advised.', 'Stop and seek care for black stools or vomiting blood.'],
    contraindications: ['Active ulcer/bleeding', 'Aspirin allergy', 'Bleeding disorders'],
  },
  {
    id: 'cetirizine',
    name: 'Cetirizine',
    genericName: 'Cetirizine',
    class: 'Antihistamine (2nd generation)',
    category: 'Allergy',
    uses: ['Allergic rhinitis', 'Sneezing', 'Itchy eyes', 'Hives'],
    dosage: {
      adult: '10 mg once daily.',
      pediatric: '2-5 years: 2.5-5 mg daily. 6+ years: 5-10 mg daily (age/weight dependent).',
      elderly: 'Consider 5 mg daily if sensitive or with kidney impairment.',
    },
    sideEffects: {
      common: ['Sleepiness (less than older antihistamines)', 'Dry mouth'],
      rare: ['Urinary retention (rare)', 'Severe allergy (very rare)'],
    },
    pregnancySafety: 'Often considered reasonable when needed; discuss if pregnant or breastfeeding.',
    interactions: ['Alcohol or sedatives (more drowsiness)'],
    warnings: ['Use caution when driving until you know how it affects you.'],
    contraindications: ['Known allergy to cetirizine or hydroxyzine'],
  },
  {
    id: 'loratadine',
    name: 'Loratadine',
    genericName: 'Loratadine',
    class: 'Antihistamine (2nd generation)',
    category: 'Allergy',
    uses: ['Allergic rhinitis', 'Hives', 'Itching'],
    dosage: {
      adult: '10 mg once daily.',
      pediatric: '2-5 years: 5 mg daily. 6+ years: 10 mg daily.',
      elderly: 'Usually same as adult; reduce dose in severe liver impairment.',
    },
    sideEffects: {
      common: ['Headache', 'Dry mouth'],
      rare: ['Fast heartbeat (rare)', 'Severe allergy (very rare)'],
    },
    pregnancySafety: 'Often used when needed; discuss if pregnant or breastfeeding.',
    interactions: ['Some antifungals/antibiotics may increase levels (less common with modern dosing)'],
    warnings: ['Typically non-drowsy, but reactions vary.'],
    contraindications: ['Known allergy to loratadine'],
  },
  {
    id: 'amoxicillin',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    class: 'Penicillin antibiotic',
    category: 'Antibiotic',
    uses: ['Ear infections', 'Sinus infections', 'Strep throat', 'Some chest infections (clinician-directed)'],
    dosage: {
      adult: 'Commonly 500 mg every 8 hours or 875 mg every 12 hours (varies by infection).',
      pediatric: 'Weight-based dosing; commonly 25-90 mg/kg/day divided (infection-dependent).',
      elderly: 'May need adjustment in kidney impairment.',
    },
    sideEffects: {
      common: ['Diarrhea', 'Nausea', 'Rash'],
      rare: ['Severe allergy (anaphylaxis)', 'Severe skin reaction', 'C. difficile diarrhea'],
    },
    pregnancySafety: 'Commonly used in pregnancy when indicated.',
    interactions: ['Warfarin (possible INR changes)', 'Allopurinol (rash risk)'],
    warnings: ['Complete the full course as prescribed.', 'Seek urgent help for breathing trouble or swelling.'],
    contraindications: ['Severe penicillin allergy'],
  },
  {
    id: 'azithromycin',
    name: 'Azithromycin',
    genericName: 'Azithromycin',
    class: 'Macrolide antibiotic',
    category: 'Antibiotic',
    uses: ['Certain respiratory infections', 'Some skin infections', 'Certain sexually transmitted infections (clinician-directed)'],
    dosage: {
      adult: 'Commonly 500 mg day 1, then 250 mg daily days 2-5 (varies by infection).',
      pediatric: 'Weight-based dosing; clinician-directed.',
      elderly: 'Caution with heart rhythm risk if predisposed.',
    },
    sideEffects: {
      common: ['Nausea', 'Diarrhea', 'Stomach pain'],
      rare: ['QT prolongation/arrhythmia risk', 'Liver injury (rare)', 'Severe allergy'],
    },
    pregnancySafety: 'Often used when needed; clinician-directed.',
    interactions: ['Other QT-prolonging drugs', 'Warfarin (possible INR changes)'],
    warnings: ['Get medical advice if you have palpitations or fainting.'],
    contraindications: ['Known azithromycin allergy'],
  },
  {
    id: 'omeprazole',
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    class: 'Proton pump inhibitor (PPI)',
    category: 'Gastrointestinal',
    uses: ['Heartburn/GERD', 'Stomach ulcers', 'Gastritis', 'Protection with NSAIDs (some cases)'],
    dosage: {
      adult: '20 mg once daily before food (dose and duration vary by condition).',
      pediatric: 'Weight-based; clinician-directed.',
      elderly: 'Use lowest effective dose; reassess long-term use.',
    },
    sideEffects: {
      common: ['Headache', 'Diarrhea', 'Abdominal pain'],
      rare: ['Low magnesium with long-term use', 'C. difficile diarrhea (rare)', 'Kidney inflammation (rare)'],
    },
    pregnancySafety: 'Often considered acceptable when needed.',
    interactions: ['Clopidogrel (reduced activation; consider alternatives)', 'Warfarin (monitor)'],
    warnings: ['If symptoms persist, reassess diagnosis and duration of therapy.'],
    contraindications: ['Known omeprazole allergy'],
  },
  {
    id: 'famotidine',
    name: 'Famotidine',
    genericName: 'Famotidine',
    class: 'H2 blocker',
    category: 'Gastrointestinal',
    uses: ['Heartburn', 'GERD', 'Ulcer symptoms'],
    dosage: {
      adult: '10-20 mg once or twice daily (OTC dosing varies).',
      pediatric: 'Weight-based; clinician-directed.',
      elderly: 'Adjust dose in kidney impairment.',
    },
    sideEffects: {
      common: ['Headache', 'Constipation'],
      rare: ['Confusion (rare, usually older adults)', 'Allergic reaction (rare)'],
    },
    pregnancySafety: 'Often used when needed.',
    interactions: ['Few major interactions; spacing may help with some drugs needing stomach acidity'],
    warnings: ['Seek care for trouble swallowing, black stools, or weight loss with heartburn.'],
    contraindications: ['Known famotidine allergy'],
  },
  {
    id: 'salbutamol',
    name: 'Salbutamol (Albuterol)',
    genericName: 'Salbutamol',
    class: 'Short-acting beta agonist (SABA)',
    category: 'Respiratory',
    uses: ['Wheezing', 'Asthma symptom relief', 'Bronchospasm'],
    dosage: {
      adult: 'Inhaler: typically 1-2 puffs every 4-6 hours as needed (follow clinician plan).',
      pediatric: 'Inhaler dosing varies by age; use spacer; clinician-directed.',
      elderly: 'Monitor for tremor and heart effects.',
    },
    sideEffects: {
      common: ['Tremor', 'Fast heartbeat', 'Nervousness'],
      rare: ['Low potassium (rare with high doses)', 'Paradoxical bronchospasm (very rare)'],
    },
    pregnancySafety: 'Commonly used when needed for asthma control.',
    interactions: ['Non-selective beta blockers may reduce effect', 'Stimulants increase heart effects'],
    warnings: ['Frequent use suggests poor control. Seek medical review.'],
    contraindications: ['Known salbutamol allergy'],
  },
  {
    id: 'budesonide_inhaler',
    name: 'Budesonide (inhaled)',
    genericName: 'Budesonide',
    class: 'Inhaled corticosteroid (ICS)',
    category: 'Respiratory',
    uses: ['Asthma control (preventer)', 'Reduce airway inflammation'],
    dosage: {
      adult: 'Dose varies by inhaler strength and severity; typically taken daily as maintenance.',
      pediatric: 'Clinician-directed; use spacer if recommended.',
      elderly: 'Same as adult; monitor oral thrush risk.',
    },
    sideEffects: {
      common: ['Hoarseness', 'Oral thrush (if mouth not rinsed)'],
      rare: ['Systemic steroid effects at very high doses (rare)'],
    },
    pregnancySafety: 'Commonly used when needed to keep asthma controlled.',
    interactions: ['Strong CYP3A4 inhibitors (can increase steroid exposure)'],
    warnings: ['Rinse mouth after use to reduce thrush risk.'],
    contraindications: ['Known budesonide allergy'],
  },
  {
    id: 'metformin',
    name: 'Metformin',
    genericName: 'Metformin',
    class: 'Biguanide',
    category: 'Diabetes',
    uses: ['Type 2 diabetes (blood sugar control)'],
    dosage: {
      adult: 'Often started low (e.g., 500 mg once daily) and increased as tolerated; follow clinician plan.',
      pediatric: 'Clinician-directed for selected cases.',
      elderly: 'Assess kidney function; adjust or avoid if kidney impairment.',
    },
    sideEffects: {
      common: ['Nausea', 'Diarrhea', 'Stomach upset (often improves over time)'],
      rare: ['Lactic acidosis (very rare; higher risk with severe kidney, liver, or heart failure)'],
    },
    pregnancySafety: 'Used in some pregnancy-related diabetes cases under clinician care.',
    interactions: ['Alcohol (increases lactic acidosis risk)', 'Contrast dye procedures (temporary hold may be advised)'],
    warnings: ['Take with meals to reduce stomach upset.', 'Tell clinicians before imaging with contrast.'],
    contraindications: ['Severe kidney impairment', 'Metabolic acidosis'],
  },
  {
    id: 'amlodipine',
    name: 'Amlodipine',
    genericName: 'Amlodipine',
    class: 'Calcium channel blocker',
    category: 'Cardiovascular',
    uses: ['High blood pressure', 'Angina (chest pain)'],
    dosage: {
      adult: 'Commonly 5-10 mg once daily.',
      pediatric: 'Selected cases; clinician-directed.',
      elderly: 'Start low and titrate due to dizziness/edema risk.',
    },
    sideEffects: {
      common: ['Ankle swelling', 'Flushing', 'Dizziness'],
      rare: ['Worsening chest pain initially (rare)', 'Allergic reaction (rare)'],
    },
    pregnancySafety: 'Clinician-directed; alternatives are often preferred depending on scenario.',
    interactions: ['Some antibiotics/antifungals can increase levels', 'Grapefruit effect is minor but varies'],
    warnings: ['Report severe swelling, fainting, or chest pain.'],
    contraindications: ['Known amlodipine allergy'],
  },
  {
    id: 'lisinopril',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    class: 'ACE inhibitor',
    category: 'Cardiovascular',
    uses: ['High blood pressure', 'Heart failure (some cases)', 'Kidney protection in diabetes (some cases)'],
    dosage: {
      adult: 'Commonly 5-40 mg once daily (titrated).',
      pediatric: 'Selected cases; clinician-directed.',
      elderly: 'Start low; monitor kidney function and potassium.',
    },
    sideEffects: {
      common: ['Dry cough', 'Dizziness'],
      rare: ['Angioedema (swelling of face/lips)', 'High potassium', 'Kidney function changes'],
    },
    pregnancySafety: 'Not safe in pregnancy. Avoid.',
    interactions: ['Potassium supplements/spironolactone (high potassium risk)', 'NSAIDs (kidney risk)'],
    warnings: ['Seek urgent care for facial swelling or trouble breathing.'],
    contraindications: ['Pregnancy', 'History of ACE inhibitor angioedema'],
  },
  {
    id: 'atorvastatin',
    name: 'Atorvastatin',
    genericName: 'Atorvastatin',
    class: 'Statin',
    category: 'Cardiovascular',
    uses: ['High cholesterol', 'Cardiovascular risk reduction (clinician-directed)'],
    dosage: {
      adult: 'Commonly 10-80 mg once daily.',
      pediatric: 'Selected cases; clinician-directed.',
      elderly: 'Monitor muscle symptoms; consider interactions.',
    },
    sideEffects: {
      common: ['Muscle aches', 'Mild stomach upset'],
      rare: ['Severe muscle injury (very rare)', 'Liver enzyme elevation (rare)'],
    },
    pregnancySafety: 'Avoid in pregnancy and breastfeeding.',
    interactions: ['Some antibiotics/antifungals increase muscle risk', 'Grapefruit can increase levels'],
    warnings: ['Report unexplained muscle pain, weakness, or dark urine.'],
    contraindications: ['Pregnancy', 'Active liver disease'],
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron',
    genericName: 'Ondansetron',
    class: 'Antiemetic (5-HT3 antagonist)',
    category: 'Gastrointestinal',
    uses: ['Nausea', 'Vomiting'],
    dosage: {
      adult: 'Commonly 4-8 mg every 8-12 hours as needed (route and dose vary).',
      pediatric: 'Weight-based; clinician-directed.',
      elderly: 'Consider QT risk and drug interactions.',
    },
    sideEffects: {
      common: ['Constipation', 'Headache'],
      rare: ['QT prolongation (rare)', 'Serotonin syndrome with serotonergic drugs (rare)'],
    },
    pregnancySafety: 'Clinician-directed; risk/benefit depends on trimester and severity.',
    interactions: ['Other QT-prolonging drugs', 'SSRIs/SNRIs (serotonin syndrome risk)'],
    warnings: ['Seek care for palpitations, fainting, or severe dizziness.'],
    contraindications: ['Known ondansetron allergy'],
  },
  {
    id: 'loperamide',
    name: 'Loperamide',
    genericName: 'Loperamide',
    class: 'Antidiarrheal',
    category: 'Gastrointestinal',
    uses: ['Acute diarrhea (non-bloody, no high fever)', 'Traveler’s diarrhea (selected cases)'],
    dosage: {
      adult: '4 mg initially, then 2 mg after each loose stool. Max 8 mg/day OTC (higher only if prescribed).',
      pediatric: 'Generally avoid in young children unless clinician-directed.',
      elderly: 'Monitor dehydration; do not delay medical review if severe.',
    },
    sideEffects: {
      common: ['Constipation', 'Abdominal cramps'],
      rare: ['Serious heart rhythm issues with overdose', 'Toxic megacolon in severe infectious diarrhea (rare)'],
    },
    pregnancySafety: 'Discuss with clinician if pregnant.',
    interactions: ['Some inhibitors can increase levels; avoid exceeding recommended dose'],
    warnings: ['Do not use with bloody diarrhea, high fever, or severe abdominal pain.'],
    contraindications: ['Bloody diarrhea or suspected severe bacterial infection without medical advice'],
  },
  {
    id: 'ors',
    name: 'Oral Rehydration Salts (ORS)',
    genericName: 'Glucose and electrolyte solution',
    class: 'Rehydration therapy',
    category: 'Gastrointestinal',
    uses: ['Dehydration from diarrhea', 'Dehydration from vomiting', 'Heat-related dehydration'],
    dosage: {
      adult: 'Sip frequently. Typical guidance is to replace losses after each loose stool (volume varies).',
      pediatric: 'Small frequent sips; continue breastfeeding/feeding. Use weight-based guidance when available.',
      elderly: 'Sip frequently; seek care early if weak, confused, or unable to keep fluids down.',
    },
    sideEffects: {
      common: ['Usually well tolerated'],
      rare: ['Overcorrection in severe kidney disease (rare; clinician-directed)'],
    },
    pregnancySafety: 'Safe and commonly recommended.',
    interactions: ['None significant'],
    warnings: ['Seek urgent care for signs of severe dehydration.'],
    contraindications: ['Severe vomiting preventing oral intake (needs medical evaluation)'],
  },
  {
    id: 'nitrofurantoin',
    name: 'Nitrofurantoin',
    genericName: 'Nitrofurantoin',
    class: 'Antibiotic (urinary)',
    category: 'Antibiotic',
    uses: ['Uncomplicated urinary tract infection (UTI), clinician-directed'],
    dosage: {
      adult: 'Commonly 100 mg twice daily for 5 days (formulation dependent).',
      pediatric: 'Weight-based; clinician-directed.',
      elderly: 'Avoid in significant kidney impairment; clinician-directed.',
    },
    sideEffects: {
      common: ['Nausea', 'Loss of appetite'],
      rare: ['Lung reaction (rare)', 'Liver injury (rare)', 'Nerve damage (rare)'],
    },
    pregnancySafety: 'Often used when indicated; avoid near term in some scenarios (clinician-directed).',
    interactions: ['Antacids containing magnesium trisilicate may reduce absorption'],
    warnings: ['Take with food to reduce nausea.'],
    contraindications: ['Severe kidney impairment', 'Known nitrofurantoin allergy'],
  },
  {
    id: 'fluconazole',
    name: 'Fluconazole',
    genericName: 'Fluconazole',
    class: 'Antifungal (azole)',
    category: 'Antifungal',
    uses: ['Yeast infections (some cases)', 'Fungal infections (clinician-directed)'],
    dosage: {
      adult: 'Often 150 mg single dose for uncomplicated vaginal yeast infection (scenario dependent).',
      pediatric: 'Clinician-directed.',
      elderly: 'Adjust in kidney impairment.',
    },
    sideEffects: {
      common: ['Nausea', 'Abdominal pain', 'Headache'],
      rare: ['Liver injury (rare)', 'Serious skin reaction (rare)', 'QT prolongation (rare)'],
    },
    pregnancySafety: 'Avoid high-dose or repeated use in pregnancy unless clinician-directed.',
    interactions: ['Warfarin', 'Certain statins', 'Some heart rhythm medicines'],
    warnings: ['Tell clinician about all medicines due to interaction risk.'],
    contraindications: ['Known fluconazole allergy'],
  },
  {
    id: 'clotrimazole',
    name: 'Clotrimazole (topical)',
    genericName: 'Clotrimazole',
    class: 'Antifungal (azole)',
    category: 'Antifungal',
    uses: ['Athlete’s foot', 'Ringworm', 'Jock itch', 'Skin yeast infections'],
    dosage: {
      adult: 'Apply a thin layer 2 times daily for 2-4 weeks depending on site.',
      pediatric: 'Use as directed; avoid eyes/mouth.',
      elderly: 'Same as adult.',
    },
    sideEffects: {
      common: ['Mild burning or irritation at application site'],
      rare: ['Severe local reaction (rare)'],
    },
    pregnancySafety: 'Topical use is generally considered low risk when needed.',
    interactions: ['None significant with topical use'],
    warnings: ['Keep area clean and dry; continue for the full course.'],
    contraindications: ['Known clotrimazole allergy'],
  },
  {
    id: 'doxycycline',
    name: 'Doxycycline',
    genericName: 'Doxycycline',
    class: 'Tetracycline antibiotic',
    category: 'Antibiotic',
    uses: ['Acne (some cases)', 'Certain respiratory infections', 'Tick-borne infections (clinician-directed)'],
    dosage: {
      adult: 'Often 100 mg once or twice daily (condition dependent).',
      pediatric: 'Typically avoided under 8 years unless specifically indicated; clinician-directed.',
      elderly: 'Generally no adjustment, but monitor tolerance.',
    },
    sideEffects: {
      common: ['Nausea', 'Photosensitivity (sunburn risk)', 'Heartburn'],
      rare: ['Esophagitis if taken without water', 'Severe allergy (rare)'],
    },
    pregnancySafety: 'Avoid in pregnancy unless no alternatives; clinician-directed.',
    interactions: ['Iron/calcium/antacids reduce absorption (separate by 2-4 hours)'],
    warnings: ['Take with a full glass of water; stay upright for 30 minutes.'],
    contraindications: ['Pregnancy (generally)', 'Tetracycline allergy'],
  },
  {
    id: 'levothyroxine',
    name: 'Levothyroxine',
    genericName: 'Levothyroxine',
    class: 'Thyroid hormone',
    category: 'Endocrine',
    uses: ['Hypothyroidism'],
    dosage: {
      adult: 'Individualized dosing based on labs; commonly taken once daily.',
      pediatric: 'Clinician-directed with regular monitoring.',
      elderly: 'Start low and go slow, especially with heart disease.',
    },
    sideEffects: {
      common: ['If dose is too high: palpitations, anxiety, tremor'],
      rare: ['Serious arrhythmia if over-replaced (rare)'],
    },
    pregnancySafety: 'Important to continue in pregnancy; dose often needs adjustment with monitoring.',
    interactions: ['Iron/calcium binders reduce absorption (separate by 4 hours)', 'Some antacids/cholestyramine'],
    warnings: ['Take on an empty stomach, same time daily, separate from supplements.'],
    contraindications: ['Untreated hyperthyroidism'],
  },
  {
    id: 'sertraline',
    name: 'Sertraline',
    genericName: 'Sertraline',
    class: 'SSRI antidepressant',
    category: 'Mental Health',
    uses: ['Depression', 'Anxiety', 'Panic disorder', 'OCD (clinician-directed)'],
    dosage: {
      adult: 'Commonly started at 25-50 mg daily and adjusted; clinician-directed.',
      pediatric: 'Selected cases; clinician-directed.',
      elderly: 'Start low; monitor sodium and interactions.',
    },
    sideEffects: {
      common: ['Nausea', 'Sleep changes', 'Sexual side effects'],
      rare: ['Serotonin syndrome (rare)', 'Low sodium (rare)', 'Bleeding risk with NSAIDs (rare)'],
    },
    pregnancySafety: 'Clinician-directed; risk/benefit depends on condition severity.',
    interactions: ['MAO inhibitors (contraindicated)', 'NSAIDs/anticoagulants (bleeding risk)'],
    warnings: ['Do not stop abruptly without advice.', 'Seek urgent care for severe agitation, fever, confusion.'],
    contraindications: ['MAO inhibitor use', 'Known sertraline allergy'],
  },
];

export const seedSymptomMap: Record<string, string[]> = {
  fever: ['paracetamol', 'ibuprofen', 'aspirin'],
  headache: ['paracetamol', 'ibuprofen', 'aspirin'],
  pain: ['paracetamol', 'ibuprofen', 'aspirin'],
  inflammation: ['ibuprofen', 'aspirin'],
  allergy: ['cetirizine', 'loratadine'],
  hives: ['cetirizine', 'loratadine'],
  heartburn: ['omeprazole', 'famotidine'],
  gerd: ['omeprazole', 'famotidine'],
  nausea: ['ondansetron', 'ors'],
  vomiting: ['ondansetron', 'ors'],
  diarrhea: ['ors', 'loperamide'],
  dehydration: ['ors'],
  uti: ['nitrofurantoin'],
  fungal: ['clotrimazole', 'fluconazole'],
  asthma: ['salbutamol', 'budesonide_inhaler'],
  wheeze: ['salbutamol', 'budesonide_inhaler'],
  cough: ['salbutamol'],
  'high blood pressure': ['amlodipine', 'lisinopril'],
  hypertension: ['amlodipine', 'lisinopril'],
  diabetes: ['metformin'],
  cholesterol: ['atorvastatin'],
  thyroid: ['levothyroxine'],
  depression: ['sertraline'],
  anxiety: ['sertraline'],
  infection: ['amoxicillin', 'azithromycin', 'doxycycline'],
};

